### ISSUE TITLE
__proto__ and length

### ISSUE THREAD

**Issue by ErikKrause** [burningmoth/burningmoth-chromelogger-firefox#1]
`__proto__` and `length` object and array properties should be removed (again). Why was this feature changed back anyway?

**Comment by tarraccas** [comment]
The regression is noted in CHANGELOG.md. Unless the object properties are processed immediately before being output then `__proto__` and `length` properties appear to be restored when the object is passed. Since all X-ChromeLogger-Data processing was consolidated to a single function but with multiple outputs ( injected script or devtools fallback ) the data including all the objects are necessarily passed.

A solution may be to explicitly define an object class without these properties (if possible) to express the data through. We'll see.
